version: '3.1'
services:
  db:

    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: zkhaliq
      MYSQL_PASSWORD: zkhaliq
      MYSQL_DATABASE: test
    ports:
      - "3310:3306"
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8090:8080"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

