server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: ucomputersa-auth
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 30
      connection-timeout: 10000
      minimum-idle: 10
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 651897155138-8vte0cv921jkb5ij8gpoait7hmcikojj.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:3000/auth/callback
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          autocommit: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
