server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
  data:
    mongodb:
      uri:


twilio:
  account-sid:
  auth-token:
  verify-service-sid: